### ISSUE TITLE
macOS 12.1: Cannot find `libPCBUSB.dylib`

### ISSUE THREAD

**Issue by andsteing** [rauc-lab/being#4]
After a fresh installation from Github I get the following error stacktrace when running the tests:

```
Traceback (most recent call last):
  File "/Users/me/git/being/setup.py", line 9, in <module>
    import being
  File "/Users/me/git/being/being/__init__.py", line 10, in <module>
    patch_pcan_on_darwin()
  File "/Users/me/git/being/being/can/pcan_darwin_patch.py", line 32, in patch_pcan_on_darwin
    lib = cdll.LoadLibrary('libPCBUSB.dylib')
  File "/Users/me/.pyenv/versions/3.9.7/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/me/.pyenv/versions/3.9.7/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libPCBUSB.dylib, 0x0006): tried: 'libPCBUSB.dylib' (no such file), '/usr/local/lib/libPCBUSB.dylib' (no such file), '/usr/lib/libPCBUSB.dylib' (no such file), '/Users/me/git/being/libPCBUSB.dylib' (no such file), '/usr/local/lib/libPCBUSB.dylib' (no such file), '/usr/lib/libPCBUSB.dylib' (no such file)
```

Note that all tests run fine when `patch_pcan_on_darwin()` is not executed (though I haven't connected any hardware to my computer).

**Comment by atheler** [comment]
Will get fixed in version 1.0.2. We should only patch if possible and necessary.

Future note: It seems that the underlying issue will be fixed with [python-can](https://github.com/hardbyte/python-can) version >= 4.0.0. So hopefully soon to be removed.
